name: Pull Request Quality Check
run-name: ${{ github.head_ref }} quality control
on:
  pull_request: 
    branches:
      - main
jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup requirements
        run: sudo apt-get -y --no-install-recommends install clang-format clang-tidy
      
      - name: Configure project
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build

      - name: Code style check
        run: |
          find ./src -name "*.cpp" | xargs clang-format --dry-run --Werror

      - name: Code lint check
        run: |
          clang-tidy $(find ./src -name "*.cpp")
  build:
    needs: static-check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Build Project
        run: cmake --build build
    
      - name: Save test artifact
        uses: actions/upload-artifact@v6
        with:
          name: SchottenTest
          path: |
            build/bin/GameTest

  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get test artifact
          uses: actions/download-artifact@v4
          with:
            name: SchottenTest
            path: build/bin

        - name: Run test artifact
          run: |
            chmod +x build/bin/GameTest
            build/bin/GameTest
